---
- hosts: all
  remote_user: user
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: transfer and unarchive file
    unarchive:
      src: http://192.168.1.1/scripts/jixian-2019.tar.gz
      dest: /tmp
      copy: no
  - name: running scripts
    command: '/usr/bin/env python /tmp/jixian-2019/main.py'
